# Generated by Django 5.1.3 on 2025-04-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0008_delete_chatnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('chat_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_return', to='chat.chatroom')),
            ],
        ),
    ]
