# Generated by Django 5.1.3 on 2025-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='has_unread_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='has_unread_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
