# Generated by Django 5.1.3 on 2025-03-27 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatnotification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_new_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='order_status',
            field=models.CharField(choices=[('new', 'New Order'), ('active', 'Active Order'), ('completed', 'Completed Order')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='order_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
