# Generated by Django 5.1.3 on 2025-04-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_is_new_order_chatroom_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
