# Generated by Django 5.1.3 on 2025-04-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_delete_chatnotification'),
        ('orders', '0002_order_orderitem_delete_orderreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='order_status',
            field=models.CharField(choices=[('new', 'New Order'), ('pending', 'Pending Order'), ('shipped', 'Shipped Order'), ('delivered', 'Delivered Order'), ('active', 'Active Order'), ('completed', 'Completed Order')], default='new', max_length=20),
        ),
    ]
