# Generated by Django 5.1.3 on 2025-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(help_text='URL of the product image from Cloudinary'),
        ),
    ]
