# Generated by Django 5.1.3 on 2024-12-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('FARMER', 'Farmer'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], help_text='ADMIN type is reserved for superusers only', max_length=20),
        ),
    ]
