# Generated by Django 5.1.3 on 2025-03-01 20:28

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default=1, error_messages={'blank': 'City field is required', 'null': 'City field is required'}, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(default=1, error_messages={'blank': 'Province field is required', 'null': 'Province field is required'}, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=users.models.generate_short_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('FARMER', 'Farmer'), ('ADMIN', 'Admin')], help_text='ADMIN type is reserved for superusers only', max_length=20),
        ),
    ]
