# Generated by Django 5.1.3 on 2024-12-08 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Unknown', error_messages={'blank': 'City field is required', 'null': 'City field is required'}, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(default='Unknown', error_messages={'blank': 'Province field is required', 'null': 'Province field is required'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
