# Generated by Django 5.1.3 on 2025-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_fullname_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the news article', max_length=255)),
                ('description', models.TextField(help_text='Brief description or summary of the article')),
                ('image', models.ImageField(help_text='Featured image for the article', upload_to='news_images/')),
                ('article_url', models.URLField(help_text='External link to the original article')),
                ('category', models.CharField(choices=[('farming_techniques', 'Farming Techniques'), ('government', 'Government'), ('climate', 'Climate'), ('technology', 'Technology'), ('sustainability', 'Sustainability'), ('general', 'General')], default='general', max_length=50)),
                ('author', models.CharField(blank=True, help_text='Author of the article', max_length=100, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the article (e.g., organization name)', max_length=100, null=True)),
                ('published_date', models.DateField(help_text='Publication date of the article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the article is visible to users')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
