# Generated by Django 5.1.3 on 2025-03-27 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newsarticle_options_remove_newsarticle_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Publication date of the article'),
        ),
    ]
