# Generated by Django 5.1.3 on 2024-12-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_city_alter_customuser_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cnic',
        ),
    ]
