# Generated by Django 5.1.3 on 2025-03-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newsarticle_options_newsarticle_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_date',
        ),
    ]
